### ISSUE TITLE
在「監看檔案變化」的發現

### ISSUE THREAD

**Issue by nadihsu** [jaceju/book-gulp-in-action#1]
hi, Jaceju:

我正在學習gulp，有嘗試參考您的作法，發現在「監看檔案變化」的這段中。
gulp.watch('assets/templates/**/*.jade', ['jade']);
會產生Task 'jade' is not in your gulpfile的警告提示

將task名稱調整成views:develop就可以囉，給您做參考。
gulp.watch('assets/templates/**/*.jade', ['views:develop']);

對了，這份文件很棒，對學習gulp很有幫助，謝謝你 :)

**Comment by jaceju** [comment]
@nadihsu 感謝你的回應，由於這份文件還屬於草稿階段，如果還有其他錯誤也請不吝指正。

**Comment by jaceju** [comment]
Fixed in 1deda519c80426d6c7e8333dd1696ec4f15230dc
